sudo: required
services: 
 - docker

 before_install:
  - docker build -t fezerik/htm-docker Dockerfile .

deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "htm-docker"
  env: "HtmDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-048536714619"
  bucket_path: "htm-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
